development:
  server: "http://dacsanvungmien.net:3000/faye"
  secret_token: "secret"
test:
  server: "http://dacsanvungmien.net:3000/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "24645ce899379a4ddaddcdeb296bd19820cc91ecba547c2167dcdfc606c0dffb"
  signature_expiration: 3600 # one hour
